preload = /home/aman/Pictures/wallpapers/wallhaven-d61yjo.jpg
preload = /home/aman/Pictures/wallpapers/wallhaven-kxmxom.jpg
preload = /home/aman/Pictures/wallpapers/wallhaven-je8vlm.jpg
preload = /home/aman/Pictures/wallpapers/wallhaven-yqmlmx.png
preload = /home/aman/Pictures/wallpapers/wallhaven-ogx5y9.jpg
preload = /home/aman/Pictures/wallpapers/wallhaven-oggw5p.png
preload = /home/aman/Pictures/wallpapers/wallhaven-d8633m.jpg
preload = /home/aman/Pictures/wallpapers/wallhaven-5y7e99.png
preload = /home/aman/Pictures/wallpapers/wallhaven-9omgp1.jpg
#if more than one preload is desired then continue to preload other backgrounds

#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
wallpaper {
    monitor = 
    path = /home/aman/Pictures/wallpapers/wallhaven-qrr21r.png
    fit_mode = cover
}

#enable splash text rendering over the wallpaper
splash = false

ipc = true
